# Generated by Django 3.2 on 2021-04-27 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=122)),
                ('receiver', models.CharField(max_length=122)),
                ('body', models.CharField(max_length=1024)),
                ('subject', models.CharField(max_length=122)),
                ('date', models.DateField()),
            ],
        ),
    ]
