# Generated by Django 3.2 on 2021-04-27 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_data'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Emails',
        ),
    ]
