# Generated by Django 3.2 on 2021-05-06 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_delete_emails'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mail_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=122)),
                ('receiver', models.CharField(max_length=122)),
                ('body', models.CharField(max_length=1024)),
                ('subject', models.CharField(max_length=122)),
                ('is_draft', models.BooleanField()),
                ('in_inbox', models.BooleanField()),
                ('in_outbox', models.BooleanField()),
                ('date', models.DateField()),
            ],
        ),
    ]
