# Generated by Django 3.2 on 2021-05-07 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_mail_detail_file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Data',
        ),
    ]
